# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pop over action sheet for iphone in swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pop over action sheet for iphone in swift
    pod 'FTPopOverMenu_Swift', '~> 0.2.0'

end
